# src/core/interfaces/i_point.py
from __future__ import annotations
from typing import Protocol, Tuple, Optional, Union
import numpy as np

Number = Union[int, float, np.integer, np.floating]


class IPoint(Protocol):
    """Protocol interface for Point-like classes."""
    
    @property
    def x(self) -> Number: ...
    
    @property
    def y(self) -> Number: ...

    # Immutable transformations
    def with_x(self, new_x: Number) -> IPoint: ...
    def with_y(self, new_y: Number) -> IPoint: ...
    def translate(self, dx: Number, dy: Number) -> IPoint: ...
    def scale(self, sx: Number, sy: Optional[Number] = None) -> IPoint: ...
    def rotate(self, angle_deg: Number, origin: Optional[IPoint] = None) -> IPoint: ...

    # Conversions
    def to_int(self) -> IPoint: ...
    def to_tuple_x_y(self) -> Tuple[Number, Number]: ...
    def to_tuple_y_x(self) -> Tuple[Number, Number]: ...
    def to_int_tuple_x_y(self) -> Tuple[int, int]: ...
    def to_int_tuple_y_x(self) -> Tuple[int, int]: ...
