# src/core/interfaces/i_region.py
from __future__ import annotations
from typing import Protocol, Tuple
from core.interfaces.i_point import IPoint

class IRegion(Protocol):
    """Protocol interface for Region-like classes."""
    
    @property
    def corner1(self) -> IPoint: ...

    @property
    def corner2(self) -> IPoint: ...

    def width(self) -> float: ...
    def height(self) -> float: ...
    def center(self) -> IPoint: ...
    def normalize(self) -> IRegion: ...
    def clamp(self, max_width: int, max_height: int) -> IRegion: ...
    def contains(self, pt: IPoint) -> bool: ...
    def to_tuple_x1_y1_x2_y2(self) -> Tuple[int, int, int, int]: ...
